default: true

# Allow arbitrary line length.
# We apply the one-sentence-per-line rule. A stence may get longer than 80 characters, especially if links are contained.
# Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
MD013: false
