title: "MADR"
desription: Markdown Any Decisions Records
repository: adr/madr
theme: just-the-docs
color_scheme: light

defaults:
  -
    scope:
      path: "**/*.md"
    values:
      layout: "page"

exclude: [Dockerfile, README.md, Gemfile, Gemfile.lock]

# Hint by https://github.com/just-the-docs/just-the-docs/issues/374#issuecomment-680273258
# Theme read from https://github.com/StylishThemes/Syntax-Themes/blob/master/pygments/css-github/
# Browse alternative themes at https://stylishthemes.github.io/Syntax-Themes/pygments/
highlight_theme: jellybeans

search_enabled: true
button: true
aux_links:
  "ADR GitHub Organization":
    - "https://adr.github.io/"
  "Code Repository":
    - "https://github.com/adr/madr/"
aux_links_new_tab: false
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/adr/madr/"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true

baseurl: ""
url: "https://adr.github.io"

plugins:
  - jekyll-titles-from-headings
