source 'https://rubygems.org'

gem "jekyll", "~> 4.2" # installed by `gem jekyll`
gem "webrick"          # required when using Ruby >= 3

gem "just-the-docs", "0.5.1"

gem 'jekyll-titles-from-headings'
