name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
    - name: Lint changelog file
      uses: avto-dev/markdown-lint@v1
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        args: './CHANGELOG.md'
    - name: Lint other files files
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
          ignore: 'CHANGELOG.md'
          config: '.markdownlint.yml'
